# This file can be used to configure GitHub funding options
# More info: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [mrarejimmyz]
# patreon: # your-patreon-username
# open_collective: # your-open-collective-username
# ko_fi: # your-ko-fi-username
# tidelift: # your-tidelift-platform/package-name
# community_bridge: # your-community-bridge-project-name
# liberapay: # your-liberapay-username
# issuehunt: # your-issuehunt-username
# otechie: # your-otechie-username
# lfx_crowdfunding: # your-lfx-crowdfunding-project-name
# custom: # your-custom-sponsorship-url
