blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/mrarejimmyz/QuadraX/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/mrarejimmyz/QuadraX/tree/main/docs
    about: Read the documentation for setup and usage guides
  - name: 📧 Email
    url: mailto:ashishregmi2017@gmail.com
    about: Contact the maintainer directly
